<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Errors on // Álex Go{,5z}</title><link>https://agonzalezro.github.io/tags/errors/</link><description>Recent content in Errors on // Álex Go{,5z}</description><generator>Hugo</generator><language>en</language><lastBuildDate>Fri, 17 Oct 2014 00:00:00 +0000</lastBuildDate><atom:link href="https://agonzalezro.github.io/tags/errors/index.xml" rel="self" type="application/rss+xml"/><item><title>How to manage multiple errors in Go</title><link>https://agonzalezro.github.io/posts/errors/</link><pubDate>Fri, 17 Oct 2014 00:00:00 +0000</pubDate><guid>https://agonzalezro.github.io/posts/errors/</guid><description>Let me start with a disclaimer, I don&amp;rsquo;t really know if this is a pattern that must be followed or it&amp;rsquo;s just a weird idea coming out of my head.
The second disclaimer is that I am pretty sure that I am not the only mind that thought about this, but I didn&amp;rsquo;t see it in use in any place. Why?
Error handling in Go has his advantages and disadvantages, for me, the most important disadvantage is the &amp;ldquo;weird&amp;rdquo; way of checking the error just after the line that can raise it.</description></item></channel></rss>